project_id_env: cloud-pan
api_token_env: b2ff29dd395485b9099c29bc73680e733f8dbe17787e729b5f0b7969621d1beed14d0802b78d4cf6
preserve_hierarchy: true

files:
  - source: /src/lang/en/*.json
    translation: /src/lang/%locale%/%original_file_name%
